### ISSUE TITLE
post request without data is sending a get request

### ISSUE THREAD

**Issue by ionimit** [J3wker/besoCurl#1]
post request without data or with empty data value is sending a get request instead
this line:
`r = besocurl.post(url, data="", headers=headers)`

results as get request and not post

workaround:
`headers = ["Content-Length: 0"]`
`r = besocurl.post(url, data="/r", headers=headers)`

**Comment by OmriBaso** [comment]
Hey ioni, 
Thanks, the issue has been fixed!
